CREATE TABLE salary_structures (
    salary_structure_id BIGINT NOT NULL AUTO_INCREMENT,
    company_id BIGINT NOT NULL,
    employee_id BIGINT NOT NULL,
    basic_salary DECIMAL(12,2) NOT NULL,
    hra DECIMAL(12,2) NOT NULL,
    special_allowance DECIMAL(12,2) NOT NULL,
    other_allowance DECIMAL(12,2) NOT NULL,
    pf_percentage DECIMAL(5,2) NOT NULL,
    esi_percentage DECIMAL(5,2) NOT NULL,
    tds_percentage DECIMAL(5,2) NOT NULL,
    effective_from DATE NOT NULL,
    active BIT NOT NULL DEFAULT b'1',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL,
    PRIMARY KEY (salary_structure_id),
    CONSTRAINT fk_salary_structures_company FOREIGN KEY (company_id) REFERENCES companies (company_id),
    CONSTRAINT fk_salary_structures_employee FOREIGN KEY (employee_id) REFERENCES employees (employee_id),
    INDEX idx_salary_structures_company_employee (company_id, employee_id),
    INDEX idx_salary_structures_deleted_at (deleted_at)
);

CREATE TABLE payroll (
    payroll_id BIGINT NOT NULL AUTO_INCREMENT,
    company_id BIGINT NOT NULL,
    employee_id BIGINT NOT NULL,
    salary_structure_id BIGINT NOT NULL,
    payroll_month INT NOT NULL,
    payroll_year INT NOT NULL,
    days_in_month INT NOT NULL,
    paid_days DECIMAL(6,2) NOT NULL,
    lop_days DECIMAL(6,2) NOT NULL,
    gross_salary DECIMAL(12,2) NOT NULL,
    pf_amount DECIMAL(12,2) NOT NULL,
    esi_amount DECIMAL(12,2) NOT NULL,
    tds_amount DECIMAL(12,2) NOT NULL,
    lop_amount DECIMAL(12,2) NOT NULL,
    total_deductions DECIMAL(12,2) NOT NULL,
    net_salary DECIMAL(12,2) NOT NULL,
    status VARCHAR(30) NOT NULL,
    notes VARCHAR(255) NULL,
    generated_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL,
    PRIMARY KEY (payroll_id),
    CONSTRAINT uk_payroll_company_employee_period UNIQUE (company_id, employee_id, payroll_month, payroll_year),
    CONSTRAINT fk_payroll_company FOREIGN KEY (company_id) REFERENCES companies (company_id),
    CONSTRAINT fk_payroll_employee FOREIGN KEY (employee_id) REFERENCES employees (employee_id),
    CONSTRAINT fk_payroll_salary_structure FOREIGN KEY (salary_structure_id) REFERENCES salary_structures (salary_structure_id),
    INDEX idx_payroll_company_period (company_id, payroll_month, payroll_year),
    INDEX idx_payroll_deleted_at (deleted_at)
);
